version: '3.9'

services:
  demoapp:
    container_name: demoapp
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./demo-app-refactored/demoapp:/demoapp:Z
    env_file:
      - ./.env
    restart: always
