services:
  demoapp:
    container_name: demoapp
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - demoapp_data:/demoapp/data
      - demoapp_static:/demoapp/static
    restart: always

volumes:
  demoapp_data:
  demoapp_static:
