version: '3.9'

services:
  demoapp:
    container_name: demoapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./demoapp:/demoapp:Z
      - ./demoapp/static/:/demoapp/static/
      - ./demoapp/uploads/:/demoapp/uploads/
      - ./demoapp/db.sqlite3/:/demoapp/db.sqlite3/
    env_file:
      - ./demoapp/demoapp/.env

