# Generated by Django 5.1.14 on 2026-04-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('objeto', models.TextField()),
                ('orgao', models.CharField(max_length=200)),
                ('sigla_orgao', models.CharField(max_length=20)),
                ('fornecedor', models.CharField(max_length=200)),
                ('valor', models.CharField(max_length=50)),
                ('data_assinatura', models.CharField(max_length=20)),
                ('vigencia', models.CharField(max_length=80)),
                ('situacao', models.CharField(max_length=50)),
                ('modalidade', models.CharField(max_length=100)),
                ('contrato_cnpj', models.CharField(max_length=500)),
                ('contrato_cnpj_masked', models.CharField(default='', max_length=200)),
                ('contrato_responsavel', models.CharField(max_length=500)),
                ('contrato_responsavel_masked', models.CharField(default='', max_length=200)),
                ('contrato_banco', models.CharField(max_length=500)),
                ('contrato_banco_masked', models.CharField(default='', max_length=200)),
                ('is_tokenized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServidorPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('orgao', models.CharField(max_length=200)),
                ('sigla_orgao', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=200)),
                ('siape', models.CharField(max_length=20)),
                ('vinculo', models.CharField(max_length=100)),
                ('admissao', models.CharField(max_length=20)),
                ('situacao', models.CharField(default='Ativo', max_length=50)),
                ('salario', models.CharField(max_length=50)),
                ('servidor_cpf', models.CharField(max_length=500)),
                ('servidor_cpf_masked', models.CharField(default='', max_length=200)),
                ('servidor_beneficios', models.CharField(max_length=500)),
                ('servidor_beneficios_masked', models.CharField(default='', max_length=200)),
                ('servidor_endereco', models.CharField(max_length=500)),
                ('servidor_endereco_masked', models.CharField(default='', max_length=200)),
                ('servidor_nascimento', models.CharField(max_length=500)),
                ('servidor_nascimento_masked', models.CharField(default='', max_length=200)),
                ('is_tokenized', models.BooleanField(default=False)),
            ],
        ),
    ]
